name: Build

on:
  push:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.6', '9.2', '9.4', '9.0', '8.10.7', ]
        cabal: ['3.10']
        os: ['ubuntu-22.04', 'ubuntu-20.04', 'macOS-latest']
        flags: [ '-with-time' ]
        include:
        - ghc: '9.0'
          cabal: '3.10'
          os: 'ubuntu-20.04'
          flags: '+with-time'
        - ghc: '8.10.7'
          cabal: '3.10'
          os: 'ubuntu-20.04'
          flags: '+with-time'

    steps:

    # Setup
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install GHC and Cabal
      uses: haskell/actions/setup@v2
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Configure project
      run: |
        cat > cabal.project.local <<EOF
        package pact-time
          documentation: True
          benchmarks: True
          tests: True
          flags: ${{ matrix.flags }}
        EOF

    # Restore Packages from Caches
    - uses: actions/cache@v3
      name: cache cabal store
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ./dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}

    # Build
    - name: Update package database
      run: cabal update
    - name: Configure build
      run: |
        cabal build all --dry-run
        cabal freeze
    - name: Install build dependencies
      run: cabal build --only-dependencies
    - name: Build library
      run: cabal build

    # Tests
    - name: Run Tests
      run: cabal test
